spring:
  application:
    name: woohakdong-server
  jwt:
    secret: fklwnvndfjlsdkjevealkekfnkevkenflwjkfjlsdjvoiwenbfklhaedsf

portone:
  rest:
    api:
      key: ${PORTONE_REST_API_KEY}
      secret: ${PORTONE_REST_API_SECRET}
nh:
  iscd: "002645"
  accessToken: "01e392673ca609a93515a86580a6343652cefae31bbeb6e1333211c4e6b446ec"
