spring:
  application:
    name: woohakdong-server

  profiles:
    default: dev
    group:
      test: h2-test, payment-test
      dev: mysql-dev, payment-portone, payment-nh, sentry
      prod: mysql-prod, payment-portone, payment-nh, sentry

  config:
    import: "application-db.yml,application-payment.yml, application-sentry.yml"

  jwt:
    secret: fklwnvndfjlsdkjevealkekfnkevkenflwjkfjlsdjvoiwenbfklhaedsf

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health-check