spring:
  application:
    name: woohakdong-server

  profiles:
    default: dev
    group:
      test: h2-test, payment-test, s3-test, redis-test
      dev: mysql-dev, payment-portone, payment-nh, sentry-dev, redis-dev
      prod: mysql-prod, payment-portone, payment-nh, sentry-prod, redis-prod

  config:
    import: "application-db.yml,application-payment.yml, application-sentry.yml"

  jwt:
    secret: fklwnvndfjlsdkjevealkekfnkevkenflwjkfjlsdjvoiwenbfklhaedsf

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL_ADDRESS}
    password: ${GOOGLE_EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health-check
cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}