name: Deploy dev server

on:
  push:
    branches:
      - "develop"
      - "WHD-24_cicd_dev-server-pipeline"
  pull_request:
    branches:
      - "develop"
      - "WHD-24_cicd_dev-server-pipeline"
  workflow_dispatch:

jobs:
  build:
    name: Build Java Project With Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t woohakdong-dev:latest \
            --output type=docker \
            .  

      - name: Check Docker images
        run: |
          docker images