name: Deploy dev server

on:
  push:
    branches:
      - "develop"
      - "WHD-24_cicd_dev-server-pipeline"
  pull_request:
    branches:
      - "develop"
      - "WHD-24_cicd_dev-server-pipeline"
  workflow_dispatch:

jobs:
  build:
    name: Build Java Project With Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        run: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build and push Docker image to Amazon ECR with Tag
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$COMMIT_SHA  \
            --push .